config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'angular-items',  to: 'portfolios#angular' #customo_scope1
  get 'ruby-items',     to: 'portfolios#rubys' #custom_scope2
  get 'portfolio/:id',  to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me',       to: 'pages#about'
  get 'contact',        to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, 
                                reject_if: lambda { |attrs| attrs['name'].blank? } #esto es una validación

  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: 'Angular')    
  end

  def self.by_position
    order("position ASC")
  end

  scope :items_de_ruby_on_rails, -> {where(subtitle: 'Ruby on Rails') } 

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||=  Placeholder.image_generator(height:600, width:400)
    self.thumb_image ||= Placeholder.image_generator(height:350, width:250)
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :show, :update, :destroy]
  layout 'portfolio'
  access all: [:show, :index], user: {except: [:destroy, :new, :edit, :create, :update, :sort]}, site_admin: :all
  
  def index
  	@portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true    
  end
  
  def angular
    @angular_items = Portfolio.angular
  end

  def rubys
    @ruby_items = Portfolio.items_de_ruby_on_rails
  end

  def new
  	@portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio_item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

   def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    # Destroy/delete the record
    @portfolio_item.destroy

    # Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was removed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body,
                                       technologies_attributes: [:name]
                                     )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2>Technolgies Used:</h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <div class="form-group">
          <%= technology_form.label :name %>
          <%= technology_form.text_field :name, class: 'form-control' %>
        </div>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card" data-id="<%= portfolio_item.id %>">
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <p class="card-text">
    <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> <%= portfolio_item.subtitle %>
  </p>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin) %>

<% @angular_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin) %>
  <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?'}  if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>  
</div>

app/views/portfolios/rubys.html.erb
<h1>Ruby Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_url %>

<% @ruby_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
  <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag @portfolio_item.main_image %>
    </div>

    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>

      <hr>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <hr>

      <h3>Technologies Used:</h3>

      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>
    </div>
  </div>
</div>